name: translate

on:
  - workflow_dispatch

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install sphinx sphinx-intl

      - name: generate .po files
        run: |
          sphinx-build -M gettext  source build
          sphinx-intl update -p build/gettext -l fr -l en

      - name: push the files
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: AUtomatic translation update




